stages:
  preprocess:
    cmd: python src/preprocess.py data/raw.csv data/processed.csv
    deps:
      - src/preprocess.py
      - data/raw.csv
    outs:
      - data/processed.csv

  train:
    cmd: python src/train.py data/processed.csv models/model.pkl
    deps:
      - src/train.py
      - data/processed.csv
    outs:
      - models/model.pkl

  evaluate:
    cmd: python src/evaluate.py data/processed.csv models/model.pkl
    deps:
      - src/evaluate.py
      - data/processed.csv
      - models/model.pkl
